title: Randompostandstuff
description: A website with a blog
header_text: Randompostandstuff
header_text_color: "#ffffff"
footer_text: Copyright 2024 Hrdv10
header_feature_image: ../uploads/pages.jpg
bannerheight: "20vmax"
navbarheight: "55px"
gridlayout: false
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
upzoom: true
fixednavbar: false
